# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  config: "classpath:config/log4j2.xml"
  
server:
  port: 8080
  
security:
  user:
    name: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/
#eureka:
#  instance:
#    hostname: registry
#    prefer-ip-address: true
#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
#  client:
#    service-url:
#      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ztgoto/spring-cloud-sample"
          force-pull: true
          search-paths: "config-repo/{application}"
#          username: ""
#          password: ""
#          repos:
#            simple: https://github.com/simple/config-repo
#            special:
#              pattern: special*/dev*,*special*/dev*
#              uri: https://github.com/special/config-repo
#            local:
#              pattern: local*
#              uri: file:/home/configsvc/config-repo
#  rabbitmq:
#    host: rabbitmq

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/zhangxd1989/spring-boot-cloud
#          search-paths: config-repo
#  rabbitmq:
#    host: rabbitmq

