# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
  config: "classpath:config/log4j2.xml"
  
server:
  port: 8140
  

